name: Jake Curran
description: "Computer Science, University of Waterloo"
meta_description: "Jake Curran - Computer Science, University of Waterloo"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://jakecurran.xyz'
google_analytics: 'UA-68791607-1'

# Details for the RSS feed generator
url:            'http://jakecurran.xyz'
author:         'Jake Curran'