# Jekyll config
safe: true
markdown: kramdown
kramdown:
  math_engine: mathjax

highlighter: rouge
paginate: 15
gems: [jekyll-paginate, jekyll-sitemap]
permalink: /blog/:title
paginate_path: blog/page:num

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - _posts/1999-12-31-test.md

# Website info
name: 'Jake Curran'
description: 'University of Waterloo, Computer Science'
meta_description: 'Jake Curran - Computer Science, University of Waterloo'

google_analytics: 'UA-79209510-3'

# Other
domain_name: 'https://jakecurran.com'
url: 'https://jakecurran.com'
baseurl: ''
logo: false
