# Jekyll config
markdown: 'redcarpet'
highlighter: 'pygments'
paginate: 15
gems: [jekyll-paginate]

# Website info
name: 'Jake Curran'
description: 'University of Waterloo, Computer Science'
meta_description: 'Jake Curran - Computer Science, University of Waterloo'

# Author info
author: 'Jake Curran'
email: 'me@jakecurran.xyz'
github: 'https://github.com/jakecurran'
linkedin: 'https://linkedin.com/in/jakecurran'

# Services
google_analytics: 'UA-68791607-1'
disqus_username: 'jakecurran'

# Other
domain_name: 'https://jakecurran.xyz'
url: 'https://jakecurran.xyz'
enforce_ssl: 'jakecurran.xyz'
baseurl: '/'
logo: false
